import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import type { McpAuthKind, McpServerDTO, McpTransport } from '@popy/shared';
import { mcpService } from '../services/mcp';
import { useMcpStore } from '../store/mcp';
import { SidebarNav } from './sidebar-nav';
import { Button, Card, CheckField, TextArea, TextField } from '../ui/controls';

export function McpPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const servers = useMcpStore((state) => state.servers);
  const reload = useMcpStore((state) => state.reload);
  useEffect(() => { void reload(); }, [reload]);
  const current = id === 'new' ? undefined : servers?.find((server) => server.id === id);
  return (
    <div className="flex min-w-0 flex-1 flex-col overflow-y-auto">
      <div className="md:hidden"><SidebarNav /></div>
      {id === undefined ? (
        <div className="p-6">
          <div className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-semibold">MCP</h1><p className="mt-1 text-sm text-[var(--muted)]">Connect and manage MCP servers.</p></div><Button onClick={() => navigate('/mcp/new')}>Add New</Button></div>
          <div className="grid gap-3">{servers?.map((server) => <Card key={server.id} className="flex items-center justify-between gap-4"><div><div className="font-medium">{server.name}</div><div className="text-sm text-[var(--muted)]">{server.transport} · {server.status}</div></div><div className="flex gap-2"><Button variant="ghost" onClick={() => void mcpService.toggle(server.id).then(() => reload())}>{server.enabled ? 'OFF' : 'ON'}</Button><Button variant="ghost" onClick={() => navigate(`/mcp/${server.id}`)}>Edit</Button></div></Card>)}{servers?.length === 0 ? <p className="py-8 text-center text-sm text-[var(--muted)]">No MCP servers yet.</p> : null}</div>
        </div>
      ) : current !== undefined || id === 'new' ? <McpEditor server={current} onDone={() => { void reload(); navigate('/mcp'); }} /> : null}
    </div>
  );
}

function McpEditor({ server, onDone }: { server?: McpServerDTO | undefined; onDone: () => void }) {
  const [name, setName] = useState(server?.name ?? ''); const [description, setDescription] = useState(server?.description ?? ''); const [transport, setTransport] = useState<McpTransport>(server?.transport ?? 'streamable-http'); const [endpoint, setEndpoint] = useState(server?.endpoint ?? ''); const [command, setCommand] = useState(server?.command ?? ''); const [args, setArgs] = useState(server?.args.join(' ') ?? ''); const [authKind, setAuthKind] = useState<McpAuthKind>(server?.authKind ?? 'none'); const [authHeader, setAuthHeader] = useState(server?.authHeader ?? ''); const [secret, setSecret] = useState(''); const [enabled, setEnabled] = useState(server?.enabled ?? true); const [timeoutMs, setTimeoutMs] = useState(String(server?.timeoutMs ?? 60000)); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [tested, setTested] = useState(server?.capabilities.length ? server.capabilities : undefined);
  async function save(event: FormEvent): Promise<void> { event.preventDefault(); setBusy(true); setMessage(''); try { const body = { name, description, transport, endpoint: transport === 'stdio' ? '' : endpoint, command: transport === 'stdio' ? command : '', args: transport === 'stdio' ? args.split(/\s+/).filter(Boolean) : [], authKind, authHeader, enabled, timeoutMs: Number(timeoutMs), ...(secret ? { env: { MCP_SECRET: secret } } : {}) }; if (server) await mcpService.update(server.id, body); else await mcpService.create(body); onDone(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save'); } finally { setBusy(false); } }
  async function test(): Promise<void> { if (server === undefined) { setMessage('Save the server first, then test the connection.'); return; } setBusy(true); try { const result = await mcpService.test(server.id); setTested(result.capabilities); setMessage(`Connected. ${result.capabilities.length} capabilities found.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Connection failed'); } finally { setBusy(false); } }
  const selectClass = 'rounded-md border border-[var(--border)] bg-[var(--input-bg)] px-3 py-2 text-[var(--screen-fg)]';
  return <form onSubmit={(event) => void save(event)} className="mx-auto w-full max-w-3xl p-5"><div className="mb-5 flex items-center justify-between"><h1 className="text-xl font-semibold">{server ? 'Edit MCP server' : 'Add MCP server'}</h1><Button variant="ghost" type="button" onClick={onDone}>Back</Button></div><Card className="grid gap-4"><TextField id="mcp-name" label="Name" value={name} onChange={(event) => setName(event.target.value)} required /><TextArea id="mcp-description" label="Description" value={description} onChange={(event) => setDescription(event.target.value)} /><label className="grid gap-1.5 text-sm text-[var(--key-fg-dim)]">Transport<select id="mcp-transport" className={selectClass} value={transport} onChange={(event) => setTransport(event.target.value as McpTransport)}><option value="streamable-http">Streamable HTTP</option><option value="sse">HTTP/SSE</option><option value="stdio">stdio</option></select></label>{transport === 'stdio' ? <><TextField id="mcp-command" label="Command" value={command} onChange={(event) => setCommand(event.target.value)} required /><TextField id="mcp-args" label="Arguments (space separated)" value={args} onChange={(event) => setArgs(event.target.value)} /></> : <TextField id="mcp-endpoint" label="Endpoint URL" value={endpoint} onChange={(event) => setEndpoint(event.target.value)} required />}<label className="grid gap-1.5 text-sm text-[var(--key-fg-dim)]">Authentication<select id="mcp-auth" className={selectClass} value={authKind} onChange={(event) => setAuthKind(event.target.value as McpAuthKind)}><option value="none">None</option><option value="bearer">Bearer token</option><option value="api-key">API key</option><option value="custom-header">Custom header</option></select></label>{authKind !== 'none' ? <><TextField id="mcp-header" label="Header name (optional)" value={authHeader} onChange={(event) => setAuthHeader(event.target.value)} /><TextField id="mcp-secret" label="Secret / token" type="password" value={secret} onChange={(event) => setSecret(event.target.value)} /></> : null}<TextField id="mcp-timeout" label="Timeout (ms)" value={timeoutMs} onChange={(event) => setTimeoutMs(event.target.value)} /><CheckField id="mcp-enabled" label="Enabled" checked={enabled} onChange={setEnabled} /><div className="flex flex-wrap gap-2"><Button type="submit" disabled={busy || !name}>{busy ? 'Saving…' : 'Save'}</Button>{server ? <Button type="button" variant="ghost" onClick={() => void test()} disabled={busy}>Test connection</Button> : null}</div>{message ? <p className="text-sm text-[var(--muted)]">{message}</p> : null}</Card>{tested ? <Card className="mt-4"><h2 className="font-medium">Discovered capabilities</h2><ul className="mt-2 text-sm text-[var(--muted)]">{tested.map((capability) => <li key={capability.id}>{capability.kind}: {capability.name}</li>)}</ul></Card> : null}</form>;
}
