import type { DefaultSkill } from './default-skills.js';

export const PUBLISH_POP_AGENT_SKILL: DefaultSkill = {
  slug: "publish-pop-agent",
  name: "Publish Pop Agent",
  description: "Prepare, publish and activate an authorized Pop Agent release batch with the configured local builder, without GitHub Actions; diagnose interrupted releases.",
  whenToUse: "Publish Pop code to GitHub, release a new version, finish a stalled publication or activate an approved release batch.",
  body: [
    "# Publish Pop Agent",
    "",
    "Use for requests to publish/release Pop's own code, ship a batch, finish an interrupted release, or activate its new version. Ordinary edits need a local commit, not a release. Follow the owner's requested scope: publishing does not automatically mean making the repository public. Existing authorization to publish/activate remains valid; do not repeatedly ask for the same approval.",
    "",
    "## Discover actual state first",
    "",
    "Locate the owner-configured development checkout and inspect its Git remote. Use pop-agent-codebase if necessary. The installed service may run an immutable generation elsewhere; an end-user installation need not have a maintainer builder. Read `AGENTS.md`, `docs/specs/Spec-Pop-General.md`, the relevant changes, and the release sections of `deploy/README.md` and `docs/specs/Spec-Pop-Installation.md`. Use the current scripts as implementation authority.",
    "",
    "Inspect `git status --short --branch`, recent commits, `VERSION`, current build processes, existing release logs, and `systemctl show pop-agent-service -p WorkingDirectory -p ActiveState`. Do not assume a previous tool timed out because the build failed; it may still be running. Do not start a second build or modify another agent's working tree while it owns the batch.",
    "",
    "The default builder state is `~/.local/share/pop-agent/release-builder` (overridden by POP_AGENT_RELEASE_HOME): `checkout`, `cache`, `releases/<commit>`, `releases/latest`, and separately protected `auth`. A lock serializes build/publication. Read the configured data and workspace locations; defaults are `~/.pop-agent` and `~/pop-agent-workspace`. Keep both intact.",
    "",
    "Derive the target GitHub repository from the reviewed checkout and current owner instructions; do not publish to a hard-coded account. Preserve existing visibility, including private repositories. Keep Actions disabled for this release workflow. The local builder uses Docker; confirm the actual deployment mode rather than assuming every installation has a Docker daemon. The current builder's CPU/RAM limits are intentional defaults; changing them is a separate decision.",
    "",
    "## Choose the smallest compatible release and prepare the batch",
    "",
    "Review all intended commits, including fixes made in other chats. Choose the next unpublished version; resume an already prepared unpublished version when appropriate. Published assets are immutable. Never replace an existing release/archive with changed bytes or force-push to hide a collision.",
    "",
    "Default to `./deploy/local-release.sh build-server` for server/web-only changes (including viewers, UI and built-in skills). This reuses verified published CLI, Desktop, setup, launcher and Node artifacts pinned in `release/clients.json`; no Mac build or installer packaging is needed. Bump root `VERSION`, root/shared/server/web/tools package versions and matching server workspace lock entries only. Keep `cli/package.json`, its lock entry, `cli/src/version.ts` and `local-access/tray/main.go` unchanged unless that component changes. Run version tooling instead of globally replacing version strings. If the client-input guard detects CLI, native, launcher, shared contract or client dependency changes, investigate compatibility and prepare a full client release; never bypass hashes or relabel existing client bytes. Update installer URLs and `--ref vVERSION` examples in `deploy/README.md` too: missing these caused a full build to fail after its tests ran. Put release notes under `## VERSION — YYYY-MM-DD`; the publisher parses that dated heading. Update generated metadata through its generator when required.",
    "",
    "Run cheap consistency checks and review the diff before committing the batch in English. In the prepared Node environment, `npm run version:check` and the installation-document test can catch release metadata mistakes early. Do not launch a second full host gate: the Docker builder owns the complete batch gate. Confirm the source checkout is clean before building.",
    "",
    "Only when rebuilding native clients for a complete release, run tools/macos-tray-artifacts.ts build on a Mac from this exact clean commit before the Linux builder. Transfer manifest.json, both native tray executables and their setup DMGs to the configured release-builder/cache/macos-tray/<commit> directory. Windows setup executables cross-compile on Linux. Missing or mismatched macOS artifacts block the default build before the gate. When the owner explicitly requests Windows-first validation, `./deploy/local-release.sh build-windows` may deliberately omit macOS PLA from that immutable version; macOS update discovery then returns 404 and restoring it requires a new version. Never infer this mode merely from missing Mac artifacts.",
    "",
    "## Build, observe, and recover",
    "",
    "From the source checkout run `./deploy/local-release.sh build-server` for server/web-only changes, `./deploy/local-release.sh build` when rebuilding clients, or the explicitly authorized `build-windows` mode, redirecting output to a stable, version-specific log such as `/tmp/pop-VERSION-release-build.log`. Poll that process and tail a bounded part of its log. Report the actual stage and recent progress, not just planning/thinking messages. A tool timeout is not a process exit.",
    "",
    "The builder performs the full gate once for the committed tree, uses dependency/native-audio caches, packages the server and either stages pinned published clients (build-server) or rebuilds clients (full build), then tests installation without development tools. A successful receipt is reusable only for the same tree and Node version within its validity period. Never fabricate a receipt or skip a failed check. Do not run the full gate again after a successful unchanged build.",
    "",
    "On failure, inspect the first actionable error and the process exit code. Fix the cause, commit the change, then rebuild; changed trees need fresh validation. Repeating the same failed command without new evidence is not recovery. If the release needs credentials or a resource the environment lacks, report that specific blocker. Avoid dumping whole tool transcripts, dependency trees, or environment variables into chat.",
    "",
    "Success requires `verified.json` for the target commit, matching manifests/hashes, and `Ready to publish`. A directory under `releases/` alone is not success. Keep logs for diagnosis. No GitHub Actions runs are needed.",
    "",
    "## Publish the verified artifacts",
    "",
    "Use `./deploy/local-release.sh publish` for the clean committed batch. It verifies the release, pushes the source and annotated tag, uploads a draft, and publishes after upload success. Authentication belongs to the builder's separate protected auth directory; it is not mounted into builds. Do not assume host `gh` exists merely because publication works. Do not print credentials or put tokens into command arguments. Use `local-release.sh auth` only when authentication actually needs setup, with the token supplied through stdin by the operator.",
    "",
    "Check the published tag, draft=false, expected assets and commit. A server-only release uploads three server assets and retains original client download sources; missing duplicated installers on the new GitHub tag is expected. Verify client downloads still resolve to their pinned artifacts. On interruption, rerun publish from the same clean verified batch: it resumes a matching tag/draft, verifies existing asset hashes and uploads only missing assets. Empty failed-upload starters can be retried. A different commit, conflicting asset or published release must stop recovery; never overwrite published bytes. Fetch remote refs afterward and verify source status. GitHub publication alone does not change the running service.",
    "",
    "## Activate with a separate supervisor",
    "",
    "For owner-approved activation, use the supported manager/supervisor handoff described in `Spec-Pop-Deployment-and-Operations.md`. Verify that its candidate is the actual prepared release: production's immutable working directory may still be the old version. Do not assume its HEAD equals the development checkout.",
    "",
    "Never wait for zero active runs while keeping this same Pop run alive: it counts as active and the waiter can block itself. Hand off a durable activation request to a supervisor outside the retiring service, then finish the turn. Do not synchronously restart the service containing the tool that must finish the installation. A background shell in the service cgroup is not necessarily independent. If this handoff cannot target the prepared artifact, state that publication is complete and external activation remains necessary; do not claim installation or bypass a rejected action.",
    "",
    "For an external operator, the verified offline installer is `tools/install-prebuilt.ts`, invoked with the managed Node 22 runtime and `POP_AGENT_SERVER_RELEASE_DIR` pointing to `releases/<commit>`. Preserve the existing data/workspace/port and network setup. Use the existing port and HTTPS edge; use `--skip-network-onboarding` only when networking is already configured and the installer contract permits it. Wait for active/queued work to drain, verify identity again, and retain rollback behavior.",
    "",
    "Private releases need an additional check: production may lack GitHub download credentials. Native client assets are fetched lazily. Before activation, use the verified release manifests to populate the durable owner-only `<data-dir>/releases/client-artifacts` cache if necessary. Validate every asset's size and SHA-256, use the cache's current naming convention, and write atomically. Do not rely on an old helper under `/tmp` surviving; inspect the current client-artifact cache implementation. No GitHub token belongs in the runtime just to serve these assets.",
    "",
    "## Evidence before saying done",
    "",
    "Verify systemd is active, its WorkingDirectory identifies the expected version/commit, `/healthz` and the PWA respond, and an owner-authenticated API request succeeds. Anonymous chat and file-download requests must remain unauthorized. Check the CLI/client manifest when the release changes packaged clients. Recheck the required repository visibility and disabled Actions through the authenticated GitHub tooling available in the environment.",
    "",
    "When changing a built-in skill, verify its installed body and enabled state after activation. Untouched built-ins follow seed updates; modified installed copies need a deliberate merge that preserves owner customizations. Report code commit, published version, installed version, validation result, and any outstanding activation/device check separately. Tell the owner to reload the PWA after activation. When the release is running and checks pass, stop: do not create another version merely for additional reassurance.",
  ].join('\n'),
};
