import type { DefaultSkill } from './default-skills.js';

/** Routed maintainer knowledge; never pinned into every conversation. */
export const PUBLISH_POP_AGENT_SKILL: DefaultSkill = {
  slug: "publish-pop-agent",
  name: "Publish Pop Agent",
  description: "Publish and activate an owner-approved Pop Agent release using the local Ubuntu Docker builder and private GitHub releases, without GitHub Actions. Diagnose interrupted builds and verify the installed version.",
  whenToUse: "Publish Pop Agent code, release a new version, finish a stalled publication, or install an approved batch. Portuguese requests: publicar seu codigo, publicar no GitHub, nova versao, concluir publicacao, ativar atualizacao.",
  body: [
    "# Publish Pop Agent",
    "",
    "Use for requests to publish/release Pop's own code, ship a batch, finish an interrupted release, or activate its new version. Ordinary edits need a local commit, not a release. Follow the owner's requested scope: publishing does not automatically mean making the repository public. Existing authorization to publish/activate remains valid; do not repeatedly ask for the same approval.",
    "",
    "## Discover actual state first",
    "",
    "On ubuntu-home the source checkout is `/home/vinicius/dev/pop-agent`. The service runs an immutable generation elsewhere. Read `AGENTS.md`, `docs/specs/Spec-Pop-General.md`, the relevant changes, and the release sections of `deploy/README.md` and `docs/specs/Spec-Pop-Installation.md`. Use the current scripts as implementation authority.",
    "",
    "Inspect `git status --short --branch`, recent commits, `VERSION`, current build processes, existing release logs, and `systemctl show pop-agent-service -p WorkingDirectory -p ActiveState`. Do not assume a previous tool timed out because the build failed; it may still be running. Do not start a second build or modify another agent's working tree while it owns the batch.",
    "",
    "The builder state is `~/.local/share/pop-agent/release-builder`: `checkout`, `cache`, `releases/<commit>`, `releases/latest`, and separately protected `auth`. A lock serializes build/publication. Production data is `~/.pop-agent`; the workspace is `~/pop-agent-workspace`. Keep both intact.",
    "",
    "GitHub repository: `viniciusbuscacio/pop-agent`. Preserve private visibility and disabled Actions unless the owner explicitly changes those requirements. Docker is used on Ubuntu for release validation; production is a system service, not that container. The current builder's CPU/RAM limits are intentional defaults; changing them is a separate decision.",
    "",
    "## Prepare one complete versioned batch",
    "",
    "Review all intended commits, including fixes made in other chats. Choose the next unpublished version; resume an already prepared unpublished version when appropriate. Published assets are immutable. Never replace an existing release/archive with changed bytes or force-push to hide a collision.",
    "",
    "Keep root `VERSION`, all workspace package versions, lockfile workspace entries, `cli/src/version.ts`, and `local-access/tray/main.go` consistent. Check current version tooling for additional fields. Update installer URLs and `--ref vVERSION` examples in `deploy/README.md` too: missing these caused a full build to fail after its tests ran. Put release notes under `## VERSION — YYYY-MM-DD`; the publisher parses that dated heading. Update generated metadata through its generator when required.",
    "",
    "Run cheap consistency checks and review the diff before committing the batch in English. In the prepared Node environment, `npm run version:check` and the installation-document test can catch release metadata mistakes early. Do not launch a second full host gate: the Docker builder owns the complete batch gate. Confirm the source checkout is clean before building.",
    "",
    "## Build, observe, and recover",
    "",
    "From the source checkout run `./deploy/local-release.sh build`, redirecting output to a stable, version-specific log such as `/tmp/pop-VERSION-release-build.log`. Poll that process and tail a bounded part of its log. Report the actual stage and recent progress, not just planning/thinking messages. A tool timeout is not a process exit.",
    "",
    "The builder performs the full gate once for the committed tree, uses dependency/native-audio caches, packages CLI and server, then tests installation without development tools. A successful receipt is reusable only for the same tree and Node version within its validity period. Never fabricate a receipt or skip a failed check. Do not run the full gate again after a successful unchanged build.",
    "",
    "On failure, inspect the first actionable error and the process exit code. Fix the cause, commit the change, then rebuild; changed trees need fresh validation. Repeating the same failed command without new evidence is not recovery. If the release needs credentials or a resource the environment lacks, report that specific blocker. Avoid dumping whole tool transcripts, dependency trees, or environment variables into chat.",
    "",
    "Success requires `verified.json` for the target commit, matching manifests/hashes, and `Ready to publish`. A directory under `releases/` alone is not success. Keep logs for diagnosis. No GitHub Actions runs are needed.",
    "",
    "## Publish the verified artifacts",
    "",
    "Use `./deploy/local-release.sh publish` for the clean committed batch. It verifies the release, pushes the source and annotated tag, uploads a draft, and publishes after upload success. Authentication belongs to the builder's separate protected auth directory; it is not mounted into builds. Do not assume host `gh` exists merely because publication works. Do not print credentials or put tokens into command arguments. Use `local-release.sh auth` only when authentication actually needs setup, with the token supplied through stdin by the operator.",
    "",
    "Check the published tag, draft=false, expected assets and commit. On an interrupted upload inspect the draft and current publisher recovery behavior; do not delete or overwrite a published release. Fetch remote refs afterward and verify source status. GitHub publication alone does not change the running service.",
    "",
    "## Activate with a separate supervisor",
    "",
    "For owner-approved activation, use the supported manager/supervisor handoff described in `Spec-Pop-Deployment-and-Operations.md`. Verify that its candidate is the actual prepared release: production's immutable working directory may still be the old version. Do not assume its HEAD equals the development checkout.",
    "",
    "Never wait for zero active runs while keeping this same Pop run alive: it counts as active and the waiter can block itself. Hand off a durable activation request to a supervisor outside the retiring service, then finish the turn. Do not synchronously restart the service containing the tool that must finish the installation. A background shell in the service cgroup is not necessarily independent. If this handoff cannot target the prepared artifact, state that publication is complete and external activation remains necessary; do not claim installation or bypass a rejected action.",
    "",
    "For an external operator, the verified offline installer is `tools/install-prebuilt.ts`, invoked with the managed Node 22 runtime and `POP_AGENT_SERVER_RELEASE_DIR` pointing to `releases/<commit>`. Preserve the existing data/workspace/port and network setup. This host uses port 8787 behind Tailscale HTTPS and `--skip-network-onboarding` for existing configuration. Wait for active/queued work to drain, verify identity again, and retain rollback behavior.",
    "",
    "Private releases need an additional check: production may lack GitHub download credentials. Native client assets are fetched lazily. Before activation, use the verified release manifests to populate the durable owner-only `~/.pop-agent/releases/client-artifacts` cache if necessary. Validate every asset's size and SHA-256, use the cache's current naming convention, and write atomically. Do not rely on an old helper under `/tmp` surviving; inspect the current client-artifact cache implementation. No GitHub token belongs in the runtime just to serve these assets.",
    "",
    "## Evidence before saying done",
    "",
    "Verify systemd is active, its WorkingDirectory identifies the expected version/commit, `/healthz` and the PWA respond, and an owner-authenticated API request succeeds. Anonymous chat and file-download requests must remain unauthorized. Check the CLI/client manifest when the release changes packaged clients. Recheck private visibility and disabled Actions through the authenticated GitHub tooling available in the environment.",
    "",
    "Report code commit, published version, installed version, validation result, and any outstanding activation/device check separately. Tell the owner to reload the PWA after activation. When the release is running and checks pass, stop: do not create another version merely for additional reassurance.",
  ].join('\n'),
};
