/* eslint-disable -- GENERATED by tools/generate-self-map.ts; do not edit. */
/** The derived self-map (popy.spec §8). Regenerate with `npm run selfmap`. */
export const SELF_MAP = [
  "## Repo map (generated -- npm run selfmap)",
  "",
  "Monorepo, npm workspaces: shared, server, web. `shared` is the wire",
  "contract (pure DTOs); `server` and `web` both import it.",
  "Key dependencies: pi 0.83.0, hono ^4.6.0, better-sqlite3 ^13.0.2, react ^19.0.0.",
  "",
  "server/src, clean architecture -- dependencies point inward only:",
  "- `application/` -- use cases and ports/ (interfaces the outer layers implement) (43 modules)",
  "- `architecture/` -- the boundary test that enforces the dependency rule (0 modules)",
  "- `domain/` -- entities, value objects and pure services -- the innermost layer (10 modules)",
  "- `infrastructure/` -- adapters: SQLite, the pi engine, vaults on disk, embeddings (48 modules)",
  "- `interface/` -- HTTP routes (Hono) and SSE -- the outer edge (23 modules)",
  "- `testing/` -- shared test harness helpers (1 module)",
  "",
  "## UI map (generated)",
  "",
  "PWA routes: /setup, /login, /recover, /chat/:chatId/artifacts, /settings/*, /, /chat/:chatId, /files, /files/:folderId.",
  "Settings sections: General, Model, Memory, Skills, Usage, Backup, Appearance, Security, About, Updates.",
  "Deep links: /settings?section=<name> opens a section directly.",
].join('\n');
