/** The derived self-map (pop-agent.spec §8). Regenerate with `npm run selfmap`. */
export const SELF_MAP = [
  "## Repo map (generated -- npm run selfmap)",
  "",
  "Monorepo, npm workspaces: shared, server, web, cli. `shared` is the wire",
  "contract (pure DTOs); `server` and `web` both import it.",
  "Key dependencies: pi 0.84.1, hono ^4.13.1, better-sqlite3 ^13.0.2, react ^19.0.0.",
  "",
  "server/src, clean architecture -- dependencies point inward only:",
  "- `application/` -- use cases and ports/ (interfaces the outer layers implement) (73 modules)",
  "- `architecture/` -- the boundary test that enforces the dependency rule (0 modules)",
  "- `domain/` -- entities, value objects and pure services -- the innermost layer (15 modules)",
  "- `infrastructure/` -- adapters: SQLite, the pi engine, vaults on disk, embeddings (67 modules)",
  "- `interface/` -- HTTP routes (Hono) and SSE -- the outer edge (34 modules)",
  "- `manager/` -- see pop-agent.spec (3 modules)",
  "- `testing/` -- shared test harness helpers (1 module)",
  "",
  "## UI map (generated)",
  "",
  "PWA routes: /setup, /login, /recover, /settings/*, /, /chat/:chatId, /files, /files/trash, /files/*, /tasks, /tasks/new, /tasks/:taskId, /skills, /skills/new, /skills/:slug, /mcp, /mcp/new, /mcp/:id.",
  "Settings sections: Server, General, Installation guide, Model, Audio, Auto-skills, Memory, Usage, Storage, Backup, Appearance, Security, About, Updates.",
  "Deep links: /settings?section=<name> opens a section directly.",
].join('\n');
